/**
 * Pivot Table Explorer - Type Definitions
 * 
 * This file contains all TypeScript interfaces and types for the PivotGrid component
 * and related data structures.
 */

// ============================================================================
// DATA MODELS
// ============================================================================

/**
 * Represents a generic data item with string keys and various value types.
 * Used as the base type for all data passed to the PivotGrid component.
 */
export interface DataItem {
  [key: string]: string | number | boolean | null | undefined;
}

// ============================================================================
// GRID CELL MODELS
// ============================================================================

/**
 * Represents a cell in the pivot grid with metadata for rendering.
 * Each cell contains a value and information about its role in the grid.
 */
export interface Cell {
  /** The display value of the cell (can be string or number) */
  value: string | number;
  
  /** Whether this cell is a header cell */
  isHeader: boolean;
  
  /** Number of rows this cell should span */
  rowSpan: number;
  
  /** Number of columns this cell should span */
  colSpan: number;
  
  /** Whether this cell is the top-left corner cell */
  isCorner?: boolean;
  
  /** Whether this cell is a row dimension label */
  isRowLabel?: boolean;
  
  /** Whether this cell is a column dimension label */
  isColumnLabel?: boolean;
  
  /** Whether this cell contains aggregated data */
  isDataCell?: boolean;
}

// ============================================================================
// PIVOT DATA MODELS
// ============================================================================

/**
 * The complete pivot data structure containing rows, columns, and the grid.
 * Generated by the PivotGrid component based on the input data and configuration.
 */
export interface PivotData {
  /** All unique row combinations from the row dimension fields */
  rows: string[][];
  
  /** All unique column combinations from the column dimension fields */
  columns: string[][];
  
  /** The 2D grid of cells to be rendered */
  grid: Cell[][];
}

// ============================================================================
// AGGREGATION TYPES
// ============================================================================

/**
 * Available aggregation functions for value fields.
 * These determine how values are combined when multiple data items
 * match the same row/column combination.
 */
export type AggregationFunction = 'sum' | 'avg' | 'count' | 'min' | 'max';

/**
 * Aggregation functions signature type.
 * All aggregation functions take an array of values and return a number.
 */
export type AggregationFunctionImpl = (
  values: (string | number | boolean | null | undefined)[]
) => number;

/**
 * Registry of all available aggregation functions.
 * Maps aggregation function names to their implementations.
 */
export type AggregationFunctionsRegistry = Record<
  AggregationFunction,
  AggregationFunctionImpl
>;

// ============================================================================
// COMPONENT PROPS
// ============================================================================

/**
 * Props for the PivotGrid component.
 * All props are optional except for the data array.
 */
export interface PivotGridProps {
  /** 
   * The data to be pivoted. Must be an array of objects with consistent keys.
   * Each object represents a data item/record.
   */
  data: DataItem[];
  
  /** 
   * Initial fields to use as row dimensions (Y-axis).
   * These fields determine the rows of the pivot table.
   */
  defaultRowFields?: string[];
  
  /** 
   * Initial fields to use as column dimensions (X-axis).
   * These fields determine the columns of the pivot table.
   */
  defaultColumnFields?: string[];
  
  /** 
   * Initial fields to aggregate.
   * These fields contain the values that will be aggregated for each cell.
   */
  defaultValueFields?: string[];
  
  /** 
   * Initial aggregation function to use.
   * Defaults to 'sum' if not specified.
   */
  defaultAggregation?: AggregationFunction;
}

// ============================================================================
// DIMENSION VALUE MODELS
// ============================================================================

/**
 * Maps field names to their unique values for a dimension.
 * Used internally to generate row and column combinations.
 */
export type DimensionValues = Record<string, string[]>;

// ============================================================================
// UTILITY TYPES
// ============================================================================

/**
 * Represents a combination of field values for a specific dimension.
 * Used to identify unique rows and columns in the pivot table.
 */
export type FieldValueCombination = string[];

/**
 * Represents the current configuration/state of the pivot table.
 * Can be used to save/load pivot configurations.
 */
export interface PivotConfiguration {
  rowFields: string[];
  columnFields: string[];
  valueFields: string[];
  aggregation: AggregationFunction;
}

// ============================================================================
// SAMPLE DATA TYPES (for documentation/examples)
// ============================================================================

/**
 * Example structure for sales data used in the demo.
 * This shows a typical use case for the PivotGrid component.
 */
export interface SalesDataItem extends DataItem {
  id?: number;
  region: string;
  product: string;
  category: string;
  quarter: string;
  sales: number;
  units: number;
  profit: number;
}

/**
 * Example structure for personnel/HR data.
 * Another common use case for pivot tables.
 */
export interface PersonnelDataItem extends DataItem {
  department: string;
  role: string;
  experience: string;
  gender: string;
  salary: number;
  count: number;
}
